
GET http://localhost:3000/api/products?quantidade=8&pagina=1

###

GET http://localhost:3000/api/product/8

###

GET http://localhost:3000/api/products?nomeCategoria=Minerais&quantidade=6&pagina=1

###

GET http://localhost:3000/api/products?nomeEfeito=Fortificação Óssea&quantidade=6&pagina=1