export const efeitos = [
  "Ganho de Massa Muscular",
  "Recuperação Muscular",
  "Saúde Imunológica",
  "Saúde do Coração e Circulação",
  "Saúde Digestiva",
  "Energia e Resistência",
  "Saúde Articular e Óssea",
  "Controle de Peso e Metabolismo",
  "Melhora do Sono",
  "Desenvolvimento Muscular",
  "Saúde Óssea",
  "Saúde Dental",
  "Saúde das Articulações",
  "Flexibilidade",
  "Melhoria do Desempenho",
  "Circulação",
  "Alívio do Estresse",
  "Foco",
  "Cognição",
  "Redução do Estresse",
  "Relaxamento",
  "Fonte de Proteína",
  "Queima de Gordura",
  "Desempenho Físico",
  "Aumento de Força",
  "Supressor de Apetite",
  "Desintoxicação",
  "Saúde Muscular",
  "Alívio do Estresse",
  "Melhoria da Memória",
  "Saúde Respiratória",
  "Suporte Imunológico"
];
