export const produtos = [
  {
    "id": "2",
    "nome": "Multivitamínico Ultra",
    "nomeCategoria": "Vitaminas",
    "nomeEfeito": ["Imunidade", "Fortificação Óssea"],
    "preco": 40.00,
    "descricao": "Uma fórmula completa para nutrição diária, repleta de vitaminas essenciais como A, C, D, E, K e minerais como zinco, cálcio e magnésio, fortalecendo a imunidade e os ossos, garantindo bem-estar e vitalidade ao longo do dia.",
    "composicao": ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina E", "Vitamina K", "Vitaminas do complexo B", "Zinco", "Cálcio", "Magnésio"],
    "imagem_url": "https://www.example.com/multivitaminico_ultra.jpg",
    "palavras_chave": ["vitaminas", "minerais", "imunidade", "bem-estar", "suplementação diária"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "3",
    "nome": "BCAA Xtend",
    "nomeCategoria": "Proteínas",
    "nomeEfeito": ["Fortalecimento Muscular", "Memória", "Imunidade"],
    "preco": 60.00,
    "descricao": "Aminoácidos cruciais para recuperação muscular rápida e eficaz, como L-leucina, L-isoleucina e L-valina, auxiliando no fortalecimento muscular, memória e imunidade, essenciais para alcançar o máximo desempenho nos treinos e garantir uma massa magra.",
    "composicao": ["L-leucina", "L-isoleucina", "L-valina", "Ácido cítrico", "Aromatizantes naturais e artificiais", "Ácido málico", "Sucralose"],
    "imagem_url": "https://www.example.com/bcaa_xtend.jpg",
    "palavras_chave": ["aminoácidos", "recuperação muscular", "desempenho", "crescimento muscular", "suplemento esportivo", "treino", "massa magra"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "8",
    "nome": "Probiótico Digestive Health",
    "nomeCategoria": "Minerais",
    "nomeEfeito": ["Imunidade"],
    "preco": 45.00,
    "descricao": "Fórmula poderosa com lactobacilos e bifidobactérias para equilibrar a flora intestinal, fortalecendo a imunidade e promovendo uma digestão saudável. Essencial para manter o intestino em harmonia e reforçar as defesas do corpo.",
    "composicao": ["Lactobacillus acidophilus", "Bifidobacterium lactis", "Lactobacillus plantarum", "FOS (Frutooligossacarídeos)"],
    "imagem_url": "https://www.example.com/probiotico_digestive_health.jpg",
    "palavras_chave": ["probiótico", "flora intestinal", "saúde digestiva", "equilíbrio", "microbiota", "imunidade", "intestino", "suplemento"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "9",
    "nome": "Suplemento Imunológico Defesa Total",
    "nomeCategoria": "Vitaminas",
    "nomeEfeito": ["Imunidade"],
    "preco": 40.00,
    "descricao": "Combinação de vitaminas como C, D, E, zinco, selênio e extrato de equinácea fortalece o sistema imunológico, proporcionando defesas sólidas contra doenças. Ideal para manter a saúde em dia e resistir a desafios diários.",
    "composicao": ["Vitamina C", "Vitamina D", "Vitamina E", "Zinco", "Selênio", "Extrato de equinácea", "Echinacea purpurea"],
    "imagem_url": "https://www.example.com/suplemento_imunologico_defesa_total.jpg",
    "palavras_chave": ["sistema imunológico", "imunidade", "defesa", "resistência", "vitaminas", "minerais", "equinácea", "fortalecimento"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "13",
    "nome": "L-Glutamina Pura",
    "nomeCategoria": "Proteínas",
    "nomeEfeito": ["Fortalecimento Muscular"],
    "preco": 25.00,
    "descricao": "Aminoácido essencial para recuperação muscular após exercícios intensos, protegendo também a saúde do trato gastrointestinal. Ideal para atletas e praticantes de atividades físicas que buscam maximizar o desempenho e acelerar a recuperação.",
    "composicao": ["L-Glutamina"],
    "imagem_url": "https://www.example.com/l_glutamina_pura.jpg",
    "palavras_chave": ["glutamina", "recuperação muscular", "saúde digestiva", "trato gastrointestinal", "aminoácido", "treino", "suplementação", "recuperação"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "16",
    "nome": "Proteína Vegetal Isolada",
    "nomeCategoria": "Proteínas",
    "nomeEfeito": ["Fortalecimento Muscular"],
    "preco": 50.00,
    "descricao": "Fonte de proteína de alta qualidade derivada de ervilha, arroz e semente de abóbora, essenciais para fortalecimento muscular e recuperação após o treino. Perfeito para vegetarianos, veganos e entusiastas da nutrição esportiva.",
    "composicao": ["Proteína isolada de ervilha", "Proteína isolada de arroz", "Proteína isolada de semente de abóbora"],
    "imagem_url": "https://www.example.com/proteina_vegetal_isolada.jpg",
    "palavras_chave": ["proteína", "vegetariano", "vegano", "proteína vegetal", "músculos", "recuperação", "nutrição esportiva"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "17",
    "nome": "Magnésio Quelato",
    "nomeCategoria": "Minerais",
    "nomeEfeito": ["Fortificação Óssea"],
    "preco": 30.00,
    "descricao": "Mineral vital para a saúde óssea e a função muscular, promovendo a absorção adequada de cálcio e fortalecendo ossos e músculos. Uma escolha inteligente para manter o corpo forte e resistente no dia a dia.",
    "composicao": ["Magnésio"],
    "imagem_url": "https://www.example.com/magnesio_quelato.jpg",
    "palavras_chave": ["magnésio", "mineral", "saúde óssea", "função muscular", "cálcio", "ossos", "musculatura"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "22",
    "nome": "Vitamina D3",
    "nomeCategoria": "Minerais",
    "nomeEfeito": ["Vitamina D", "Imunidade", "Fortificação Óssea"],
    "preco": 20.00,
    "descricao": "Importante para a saúde óssea, a vitamina D3 também fortalece a imunidade, garantindo proteção contra doenças. Essencial para aqueles que buscam manter ossos fortes e um sistema imunológico robusto.",
    "composicao": ["Vitamina D3"],
    "imagem_url": "https://www.example.com/vitamina_d3.jpg",
    "palavras_chave": ["vitamina D", "saúde óssea", "imunidade", "sol", "vitamina solar"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "25",
    "nome": "Suplemento de Ômega-3",
    "nomeCategoria": "Ômega-3",
    "nomeEfeito": ["Memória"],
    "preco": 35.00,
    "descricao": "Ácidos graxos essenciais provenientes do óleo de peixe, ideais para promover a saúde cardiovascular e cerebral. Protege o coração e melhora a função cognitiva, garantindo um estilo de vida mais saudável e equilibrado.",
    "composicao": ["Óleo de peixe"],
    "imagem_url": "https://www.example.com/suplemento_omega3.jpg",
    "palavras_chave": ["ômega-3", "ácidos graxos", "saúde cardiovascular", "saúde cerebral", "gorduras saudáveis"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  },
  {
    "id": "30",
    "nome": "Valeriana Natural",
    "nomeCategoria": "Vitaminas",
    "nomeEfeito": ["Relaxante"],
    "preco": 15.00,
    "descricao": "Extrato natural de valeriana, conhecido por seus efeitos relaxantes e propriedades indutoras do sono. Ajuda a combater a ansiedade, promovendo tranquilidade e um sono reparador. Uma opção segura e natural para melhorar a qualidade do sono.",
    "composicao": ["Extrato de raiz de valeriana"],
    "imagem_url": "https://www.example.com/valeriana_natural.jpg",
    "palavras_chave": ["valeriana", "sono", "ansiedade", "relaxamento", "insônia", "tranquilidade", "ervas", "extrato natural"],
    "imagens": [
      {
        nomeImagem: "Imagem do Produto 01",
        urlImagemOriginal: "",
        urlImagemReduzida: "",
        urlImagemMaior: "",
      },
    ],
  }
];
