export const debounce = {
  "vitaminas": [1, 8],
  "minerais": [1, 8],
  "imunidade": [1, 3, 4],
  "bem-estar": [1],
  "suplementação diária": [1],
  "aminoácidos": [2, 5],
  "recuperação muscular": [2, 5],
  "desempenho": [2],
  "crescimento muscular": [2],
  "suplemento esportivo": [2],
  "treino": [2],
  "massa magra": [2],
  "saúde digestiva": [3, 5],
  "equilíbrio": [3],
  "microbiota": [3],
  "intestino": [3],
  "probiótico": [3],
  "flora intestinal": [3],
  "sistema imunológico": [4],
  "defesa": [4],
  "resistência": [4],
  "equinácea": [4],
  "fortalecimento": [4],
  "glutamina": [5],
  "saúde do trato gastrointestinal": [5],
  "aminoácido": [5],
  "suplementação": [5],
  "proteína": [6],
  "vegetariano": [6],
  "vegano": [6],
  "proteína vegetal": [6],
  "músculos": [6],
  "nutrição esportiva": [6],
  "saúde óssea": [1, 7, 8],
  "sol": [8],
  "vitamina solar": [8],
  "saúde cardiovascular": [9],
  "saúde cerebral": [9],
  "gorduras saudáveis": [9],
  "ômega-3": [9],
  "ácidos graxos": [9],
  "sono": [10],
  "ansiedade": [10],
  "relaxamento": [10],
  "insônia": [10],
  "tranquilidade": [10],
  "ervas": [10],
  "extrato natural": [10],
  "Vitaminas e Minerais": [1, 8],
  "Aminoácidos e BCAAs": [2, 5],
  "Saúde Digestiva": [3],
  "Saúde Imunológica": [4],
  "Proteínas": [6],
  "Minerais": [7],
  "Óleos e Ômegas": [9],
  "Ervas e Extratos": [10],
  "Fortificação óssea": [1, 7, 8],
  "Vitamina D": [8],
  "Fortalecimento Muscular": [2, 5, 6],
  "Relaxante": [10]
}
